services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: digit-recognition-frontend
    ports:
      - "${VITE_FRONTEND_PORT:-3000}:${VITE_FRONTEND_PORT:-3000}"
    environment:
      - VITE_FRONTEND_HOST=0.0.0.0
      - VITE_FRONTEND_PORT=${VITE_FRONTEND_PORT:-3000}
      - BACKEND_HOST=${BACKEND_HOST:-backend}
      - BACKEND_PORT=${BACKEND_PORT:-5000}
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    networks:
      - digit-recognition-network
    restart: unless-stopped

volumes:
  frontend_node_modules:

networks:
  digit-recognition-network:
    driver: bridge

