name: CD - Project image building

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Docker compose build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build Docker images
      run: |
        docker compose build