name: CI - black/isort formatting check + backend/frontend tests

on:
  push:
    branches: [ main, nk/ci-cd ]
  pull_request:
    branches: [ main, nk/ci-cd ]
    
jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}

      - name: Install backend deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Check formatting (black/isort)
        run: |
          pip install black isort
          black --line-length=120 --check .
          isort --check-only .

      - name: Run backend tests
        run: |
          cd backend
          pytest -q

      - name: Run frontend tests
        run: |
          make test

          